repos:
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.28.4
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
  - repo: https://github.com/mozilla/sops-pre-commit
    rev: v0.0.14
    hooks:
      - id: sops-encryption
        files: ^(secrets/|clusters/.*/secrets/).+\.ya?ml$
