apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-providers
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  source:
    repoURL: https://github.com/tekenstam/k8s-homelab
    targetRevision: main
    path: apps/infra/crossplane/providers/manifests
  syncPolicy:
    automated: { prune: true, selfHeal: true }
