apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-issuers
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  source:
    repoURL: https://github.com/tekenstam/k8s-homelab
    targetRevision: main
    path: apps/infra/cert-manager/issuers/manifests
  syncPolicy:
    automated: { prune: true, selfHeal: true }
