apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infra/metallb/application.yaml
  - infra/metallb/config/application.yaml
  - infra/ingress-nginx/application.yaml
  - infra/cert-manager/application.yaml
  - infra/cert-manager/issuers/application.yaml
  - infra/external-dns/application.yaml
  - infra/longhorn/application.yaml
  - infra/secrets/application.yaml
  - platform/argocd/application.yaml
