apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-onprem
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: https://github.com/tekenstam/k8s-homelab
    targetRevision: main
    path: secrets/onprem
    kustomize:
      buildOptions: "--enable-alpha-plugins"
  syncPolicy:
    automated: { prune: true, selfHeal: true }
